### PR TITLE
WebSocket PipeWriter can write messages as text.

### LINKED ISSUE #719: Opt-in support for the `WebSocket` wrapper(s) to send messages as "Text"?
Considering this spot:
https://github.com/dotnet/Nerdbank.Streams/blob/3ec3e25ba48f3d59fe8c1220563d8fe71a17b8d8/src/Nerdbank.Streams/PipeExtensions.cs#L339

It sends using `WebSocketMessageType.Binary`, but this wrapper is a pretty decent way to connect `System.Text.Json` and `System.IO.Pipelines` together over a web socket.  Reading works as you'd expect, and writing stuff should look like this:
```csharp
PipeWriter writer = someWebSocket.UsePipe().Output;

// sending an arbitrary object across the Web Socket:
await JsonSerializer.SerializeAsync(writer.AsStream(true), value, s_jsonSerializerOptions, cancellationToken);

// or if I've buffered the UTF-8 bytes already:
await writer.WriteAsync(bytes, cancellationToken);
```

But of course, JSON is "text", so if I try to send this message to a receiver who treats "text" differently than "binary", they might not like what they see.  My specific use case is to chat with a [ArchipelagoMW/Archipelago](https://github.com/ArchipelagoMW/Archipelago) server: it calls [JSONDecoder.decode](https://docs.python.org/3/library/json.html#json.JSONDecoder.decode), which barfs if it gets `bytes` instead of a `str`.

I wonder if it would make sense to have something like this?
```csharp
PipeWriter writer = someWebSocket.UsePipe(messageType: WebSocketMessageType.Text).Output;
```
`UsePipe` would probably validate that the `messageType` is either `Text` or `Binary`, and I don't know if it's totally worth it to have the writer loop do like UTF-8 validation or anything like that... but as this is the only thing stopping me from using the helpers from `Nerdbank.Streams` as-is (and it's a hard blocker for my use case), I figured I'd drop in this suggestion before moving on.

### PR DESCRIPTION
**Pull request by airbreather**
Resolves #719

I'm not sure it's possible to satisfy the public API analyzers with a new overload of `UsePipeWriter` (at least):
- It's already overloaded for `Stream` vs. `WebSocket`
- Adding an overload with new optional parameters **probably** means making the parameters no longer optional in the existing `WebSocket` overload.  I'm not **entirely** sure it's possible to do this within the existing versions of the analyzers (I tried the `*REMOVED*` trick noted [here](https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md#note) without getting very far... if it's possible, then I'd probably figure it out eventually, but see next for why I gave up:)
- Even if I somehow managed to deal with the previous bullet point, the `Stream` overload then raises [RS0027: API with optional parameter(s) should have the most parameters amongst its public overloads](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md#rs0027-api-with-optional-parameters-should-have-the-most-parameters-amongst-its-public-overloads).

Now, because these are extension methods and intended to be invoked as such, I'm pretty sure I could argue a case for suppressing the rules that wouldn't have applied if these had been instance methods on the types instead, but overall the path of least resistance for me right now seems to be to just add `Utf8Text` tastefully into the method names.

FWIW, I'm creating this as a draft, because along the way I discovered what I **think** is a very bad, very fundamental issue with the fundamental way that this library does `PipeWriter`-to-`WebSocket`.  I still haven't isolated that other issue yet, and I'm still getting used to working with `System.IO.Pipelines` and its idiosyncrasies so it's very possible that it's nothing (maybe even the bug is on the receiver side)... but I don't want to commit to a proposal that adds more public APIs here until I get to the bottom of that other issue.

### CODE REVIEW

**Review by AArnott — COMMENTED** [review]
Thanks for this work. Let me know if you want to collaborate on whatever the fundamental concerning issue is. I'm sure we can work out the overload issue. A unique method name isn't a bad way to go, as I see you've don.

**Comment by airbreather** [comment]
@dotnet-policy-service agree

**Comment by airbreather** [comment]
> Let me know if you want to collaborate on whatever the fundamental concerning issue is.

I **think** I sorted out my thoughts on #726, so we can continue the conversation over there.

Thinking through it, I came up with what I think are the 3 main reasonable ways it can go, none of which should affect or be affected by this — at least not enough that would cause me any **major** regrets if I were in your shoes — so as far as this PR goes, it's good to go.

**Review by AArnott — COMMENTED** [review]
Thanks!

**Pull request merged**
